### ISSUE TITLE
Got hash can't render

### ISSUE THREAD

**Issue by AlexanderMatveev** [galdor/go-thumbhash#1] opened 2023-03-24 23:19 UTC
I just got hash `CQgKBIBgh3h3h3iHeIcAAAAAAA==` which can't rendered by browser:

![Example](data:image/png;base64,CQgKBIBgh3h3h3iHeIcAAAAAAA==)

```go
file, err := os.Open("...")
if err != nil {
	log.Fatal(err)
}
img, _, err := image.Decode(file)
if err != nil {
	log.Fatal(err)
}
hash := thumbhash.EncodeImage(img)
print(base64.StdEncoding.EncodeToString(hash)
// CQgKBIBgh3h3h3iHeIcAAAAAAA==
```

**Comment by galdor** [comment] 2023-03-25 14:52
If you test the `thumbhash` program in the repository, you'll see that this hash is decoded without any issue:

```
make build
./bin/thumbhash decode-image tmp.png CQgKBIBgh3h3h3iHeIcAAAAAAA==
```

I get the following image:

![image](https://user-images.githubusercontent.com/37804/227724774-303bad47-c963-4c56-be02-25e09666d096.png)

There might be a problem with the way you use the Javascript library.

**Comment by AlexanderMatveev** [comment] 2023-03-25 15:27
@galdor I expected that the resulting hash could be immediately saved to the database and later substituted into the `src` attribute, which the browser itself would decode. Your hash example also fails when used like this:

![CQgKBIBgh3h3h3iHeIcAAAAAAA==](data:image/png;base64,CQgKBIBgh3h3h3iHeIcAAAAAAA==)

<img width="1366" alt="Снимок экрана 2023-03-25 в 18 26 57" src="https://user-images.githubusercontent.com/1456669/227726687-ca3d8740-3a20-4dec-8849-8bf453c61f80.png">

**Comment by galdor** [comment] 2023-03-25 15:39
Ah I understand the confusion. You cannot do that. As the [Thumbpage page](https://evanw.github.io/thumbhash/) explains, the hash does not contain an image, it contains the binary representation of a set of numeric parameters that can be used to recreate an image.

In the browser, you can use the [official Javascript library](https://github.com/evanw/thumbhash/tree/main/js) to decode the hash and generate the image. There is a good example in the source code of the github.io page.

**Comment by galdor** [comment] 2023-03-25 16:10
I'm closing the issue seems this is not a bug.

**Closed as completed by galdor** 2023-03-25 16:10 UTC

**Comment by AlexanderMatveev** [comment] 2023-03-25 19:39
I believe that such processing should not be done in the browser. Especially in this context, because one of the tasks that the display of thumbnails solves is to improve UX. I will move further in the direction of doing it on the backend and putting it in storage.

Thank you for your response.

**Comment by AlexanderMatveev** [comment] 2023-03-27 16:19
To anyone who got here with a task similar to mine:

```go
file, err := os.Open("...")
if err != nil {
	log.Fatal(err)
}
img, _, err := image.Decode(file)
if err != nil {
	log.Fatal(err)
}
_ = file.Close()
hash := thumbhash.EncodeImage(img)
thumb, err := thumbhash.DecodeImageWithCfg(hash, thumbhash.DecodingCfg{
	BaseSize: 12, // result width
})
if err != nil {
	log.Fatal(err)
}
buf := new(bytes.Buffer)
if err := png.Encode(buf, thumb); err != nil {
	log.Fatal(err)
}
thumbEncoded := base64.StdEncoding.EncodeToString(buf.Bytes())
// thumbEncoded is your gem <3
```

**Comment by RichardLindhout** [comment] 2023-05-26 13:28
@AlexanderMatveev thank you, I think this should be maybe part of the library
